package kr.imcf.mybatis.domain;

import java.util.Date;

public class TblAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.id
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.created_date
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.modified_date
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    private Date modifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.access_token
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    private String accessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.email
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.is_auth
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    private Byte isAuth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.password
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.platform_type
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    private String platformType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.profile_image
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    private String profileImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.refresh_token
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    private String refreshToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.role
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.user_name
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.recv_mail
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    private Byte recvMail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.id
     *
     * @return the value of tbl_account.id
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.id
     *
     * @param id the value for tbl_account.id
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.created_date
     *
     * @return the value of tbl_account.created_date
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.created_date
     *
     * @param createdDate the value for tbl_account.created_date
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.modified_date
     *
     * @return the value of tbl_account.modified_date
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.modified_date
     *
     * @param modifiedDate the value for tbl_account.modified_date
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.access_token
     *
     * @return the value of tbl_account.access_token
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.access_token
     *
     * @param accessToken the value for tbl_account.access_token
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.email
     *
     * @return the value of tbl_account.email
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.email
     *
     * @param email the value for tbl_account.email
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.is_auth
     *
     * @return the value of tbl_account.is_auth
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public Byte getIsAuth() {
        return isAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.is_auth
     *
     * @param isAuth the value for tbl_account.is_auth
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public void setIsAuth(Byte isAuth) {
        this.isAuth = isAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.password
     *
     * @return the value of tbl_account.password
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.password
     *
     * @param password the value for tbl_account.password
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.platform_type
     *
     * @return the value of tbl_account.platform_type
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public String getPlatformType() {
        return platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.platform_type
     *
     * @param platformType the value for tbl_account.platform_type
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public void setPlatformType(String platformType) {
        this.platformType = platformType == null ? null : platformType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.profile_image
     *
     * @return the value of tbl_account.profile_image
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public String getProfileImage() {
        return profileImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.profile_image
     *
     * @param profileImage the value for tbl_account.profile_image
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public void setProfileImage(String profileImage) {
        this.profileImage = profileImage == null ? null : profileImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.refresh_token
     *
     * @return the value of tbl_account.refresh_token
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.refresh_token
     *
     * @param refreshToken the value for tbl_account.refresh_token
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.role
     *
     * @return the value of tbl_account.role
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.role
     *
     * @param role the value for tbl_account.role
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.user_name
     *
     * @return the value of tbl_account.user_name
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.user_name
     *
     * @param userName the value for tbl_account.user_name
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.recv_mail
     *
     * @return the value of tbl_account.recv_mail
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public Byte getRecvMail() {
        return recvMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.recv_mail
     *
     * @param recvMail the value for tbl_account.recv_mail
     *
     * @mbg.generated Mon Apr 11 22:51:46 KST 2022
     */
    public void setRecvMail(Byte recvMail) {
        this.recvMail = recvMail;
    }
}